### ISSUE TITLE
Update to jscsrc

### ISSUE THREAD

**Issue by dylancwood** [cdaringe/coins-validate#2]
Please add the following to the .jscsrc template:
```
  "requireSpacesInAnonymousFunctionExpression": {
        "beforeOpeningCurlyBrace": true
    },
    "disallowSpacesInFunction": {
        "beforeOpeningRoundBrace": true,
        "beforeopeningCurlyBrace": false
    },
```
This will keep in accordance with airbnb style guide on functions (it appears that the latest version of jscs is enforcing a space between `function` and `()`, which is not correct).

**Comment by cdaringe** [comment]
https://github.com/cdaringe/coins-validate/commit/2e8cdcb8ddf207c56b3de7a2424fee5322e4bfee
