### ISSUE TITLE
Require padding after blocks true?

### ISSUE THREAD

**Issue by dylancwood** [cdaringe/coins-validate#3]
https://github.com/cdaringe/coins-validate/blob/master/templates/.jscsrc#L11

This has been 'true' for quite some time. Should we change it now?

**Comment by cdaringe** [comment]
> This has been 'true' for quite some time

it has, but not necessarily by usage.  the only notable consumers (and thus visibility) has been nodeapi.  i'd claim that only yourself have really had input into those rules, and thus by first adoption, effectively "laid stake" to the set (which is fine--we needed to start somewhere with this whole process!).

IMHO, the presence of the file invites change.  per my [proposal](https://docs.google.com/document/d/1Y2BQxAzdZvdwmQQqkcFuybrj89wCRL3wtGpp0VSJiMI/edit) removing dev input at the rule level removes this conversation from happening, which now that we are doing more and more `oncommit` validation in new projects, is sure to surface again.

regardless, i should have PR'd.

this rule allows

```js
var a = [
    { a: 0 },
    { b: 1 }
];
```

vs being forced to drop a newline

```js
var a = [
    { a: 0 },
+
    { b: 1 }
];
```
